name: run-tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                php: [7.4]
                laravel: [8.*, 7.*]
                framework: [tailwind, tailwind-2, bootstrap-4]
                dependency-version: [prefer-lowest, prefer-stable]
                include:
                    -   laravel: 8.*
                        testbench: 6.*
                        livewire: ^2.0
                    -   laravel: 7.*
                        testbench: 5.*
                        livewire: ^1.3.2

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.framework }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Cache dependencies
                uses: actions/cache@v2
                with:
                    path: ~/.composer/cache/files
                    key: dependencies-laravel-${{ matrix.laravel }}-livewire-${{ matrix.livewire }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, mysql, mysqli, pdo_mysql
                    coverage: none

            -   name: Install dependencies
                run: |
                    composer require "laravel/framework:${{ matrix.laravel }}" "livewire/livewire:${{ matrix.livewire }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                    composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

            -   name: Execute tests
                env:
                    FORM_COMPONENTS_FRAMEWORK: ${{ matrix.framework }}
                run: vendor/bin/phpunit